# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Sudoku Sandbox - Build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 flake8-annotations mypy

    - name: Run Static Code Analysis (flake8)
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F5,F63,F7,F82,F841 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --ignore=ANN101,ANN102 --exit-zero --max-complexity=10 --max-line-length=130 --statistics

    - name: Run Static Code Analysis (mypy)
      run: |
        mypy -p sudoku --install-types --non-interactive

  test-execution:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macOS-latest"]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{matrix.python-version}}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r test-requirements.txt

    - name: Run Unit & Integration Tests (pytest)
      run: |
        python -m pytest --cov=sudoku tests
